In [2]:
import pandas as pd
import requests
from datetime import datetime
import os

## Berlin

In [3]:
latitude = 52.52
longitude = 13.24
API_key = os.getenv("OPENWEATHER_API_KEY")

url = f"https://api.openweathermap.org/data/2.5/forecast?lat={latitude}&lon={longitude}&appid={API_key}"

response = requests.get(url)
json = response.json()

print(json)

{'cod': '200', 'message': 0, 'cnt': 40, 'list': [{'dt': 1779969600, 'main': {'temp': 292.37, 'feels_like': 291.6, 'temp_min': 292.37, 'temp_max': 294.11, 'pressure': 1025, 'sea_level': 1025, 'grnd_level': 1019, 'humidity': 48, 'temp_kf': -1.74}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03d'}], 'clouds': {'all': 32}, 'wind': {'speed': 3.89, 'deg': 304, 'gust': 4.08}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-28 12:00:00'}, {'dt': 1779980400, 'main': {'temp': 294.39, 'feels_like': 293.61, 'temp_min': 294.39, 'temp_max': 295.83, 'pressure': 1024, 'sea_level': 1024, 'grnd_level': 1019, 'humidity': 40, 'temp_kf': -1.44}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02d'}], 'clouds': {'all': 22}, 'wind': {'speed': 4.07, 'deg': 301, 'gust': 3.99}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-28 15:00:00'}, {'dt': 1779991200, 'main': {'temp': 293.78, 'feels_like': 293.23, 'temp_min': 293.78, 'temp_max': 293.78, 'pressure': 1024, 'sea_level': 1024, 'grnd_level': 1019, 'humidity': 51, 'temp_kf': 0}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02d'}], 'clouds': {'all': 16}, 'wind': {'speed': 3.8, 'deg': 294, 'gust': 5.1}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-28 18:00:00'}, {'dt': 1780002000, 'main': {'temp': 288.74, 'feels_like': 288.16, 'temp_min': 288.74, 'temp_max': 288.74, 'pressure': 1026, 'sea_level': 1026, 'grnd_level': 1020, 'humidity': 69, 'temp_kf': 0}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02n'}], 'clouds': {'all': 13}, 'wind': {'speed': 1.53, 'deg': 20, 'gust': 2.3}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-05-28 21:00:00'}, {'dt': 1780012800, 'main': {'temp': 287.35, 'feels_like': 286.68, 'temp_min': 287.35, 'temp_max': 287.35, 'pressure': 1025, 'sea_level': 1025, 'grnd_level': 1020, 'humidity': 71, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03n'}], 'clouds': {'all': 43}, 'wind': {'speed': 1.42, 'deg': 148, 'gust': 1.88}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-05-29 00:00:00'}, {'dt': 1780023600, 'main': {'temp': 284.6, 'feels_like': 283.79, 'temp_min': 284.6, 'temp_max': 284.6, 'pressure': 1025, 'sea_level': 1025, 'grnd_level': 1020, 'humidity': 76, 'temp_kf': 0}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02d'}], 'clouds': {'all': 22}, 'wind': {'speed': 1.59, 'deg': 191, 'gust': 2.46}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-29 03:00:00'}, {'dt': 1780034400, 'main': {'temp': 288.83, 'feels_like': 287.99, 'temp_min': 288.83, 'temp_max': 288.83, 'pressure': 1025, 'sea_level': 1025, 'grnd_level': 1020, 'humidity': 59, 'temp_kf': 0}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02d'}], 'clouds': {'all': 18}, 'wind': {'speed': 1.73, 'deg': 217, 'gust': 2.32}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-29 06:00:00'}, {'dt': 1780045200, 'main': {'temp': 294.22, 'feels_like': 293.35, 'temp_min': 294.22, 'temp_max': 294.22, 'pressure': 1024, 'sea_level': 1024, 'grnd_level': 1019, 'humidity': 37, 'temp_kf': 0}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02d'}], 'clouds': {'all': 24}, 'wind': {'speed': 2.12, 'deg': 245, 'gust': 2.72}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-29 09:00:00'}, {'dt': 1780056000, 'main': {'temp': 297.82, 'feels_like': 297.05, 'temp_min': 297.82, 'temp_max': 297.82, 'pressure': 1023, 'sea_level': 1023, 'grnd_level': 1018, 'humidity': 27, 'temp_kf': 0}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02d'}], 'clouds': {'all': 14}, 'wind': {'speed': 2.91, 'deg': 278, 'gust': 3.58}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-29 12:00:00'}, {'dt': 1780066800, 'main': {'temp': 298.64, 'feels_like': 297.98, 'temp_min': 298.64, 'temp_max': 298.64, 'pressure': 1021, 'sea_level': 1021, 'grnd_level': 1016, 'humidity': 28, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 9}, 'wind': {'speed': 3.76, 'deg': 285, 'gust': 4.69}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-29 15:00:00'}, {'dt': 1780077600, 'main': {'temp': 294.65, 'feels_like': 294.37, 'temp_min': 294.65, 'temp_max': 294.65, 'pressure': 1020, 'sea_level': 1020, 'grnd_level': 1015, 'humidity': 58, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 25}, 'wind': {'speed': 2.07, 'deg': 317, 'gust': 3.86}, 'visibility': 10000, 'pop': 0.2, 'rain': {'3h': 0.33}, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-29 18:00:00'}, {'dt': 1780088400, 'main': {'temp': 291.25, 'feels_like': 291.05, 'temp_min': 291.25, 'temp_max': 291.25, 'pressure': 1020, 'sea_level': 1020, 'grnd_level': 1015, 'humidity': 74, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10n'}], 'clouds': {'all': 58}, 'wind': {'speed': 2.34, 'deg': 258, 'gust': 4.47}, 'visibility': 10000, 'pop': 0.2, 'rain': {'3h': 0.13}, 'sys': {'pod': 'n'}, 'dt_txt': '2026-05-29 21:00:00'}, {'dt': 1780099200, 'main': {'temp': 290.27, 'feels_like': 290.49, 'temp_min': 290.27, 'temp_max': 290.27, 'pressure': 1019, 'sea_level': 1019, 'grnd_level': 1013, 'humidity': 94, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10n'}], 'clouds': {'all': 79}, 'wind': {'speed': 2.39, 'deg': 258, 'gust': 9.54}, 'visibility': 10000, 'pop': 1, 'rain': {'3h': 2.99}, 'sys': {'pod': 'n'}, 'dt_txt': '2026-05-30 00:00:00'}, {'dt': 1780110000, 'main': {'temp': 289.65, 'feels_like': 289.78, 'temp_min': 289.65, 'temp_max': 289.65, 'pressure': 1018, 'sea_level': 1018, 'grnd_level': 1013, 'humidity': 93, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 100}, 'wind': {'speed': 3.42, 'deg': 277, 'gust': 11.1}, 'visibility': 10000, 'pop': 0.06, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-30 03:00:00'}, {'dt': 1780120800, 'main': {'temp': 290.56, 'feels_like': 290.52, 'temp_min': 290.56, 'temp_max': 290.56, 'pressure': 1018, 'sea_level': 1018, 'grnd_level': 1013, 'humidity': 83, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 88}, 'wind': {'speed': 3.98, 'deg': 307, 'gust': 6.22}, 'visibility': 10000, 'pop': 0.75, 'rain': {'3h': 1.05}, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-30 06:00:00'}, {'dt': 1780131600, 'main': {'temp': 294.03, 'feels_like': 293.51, 'temp_min': 294.03, 'temp_max': 294.03, 'pressure': 1018, 'sea_level': 1018, 'grnd_level': 1013, 'humidity': 51, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 8}, 'wind': {'speed': 5.19, 'deg': 307, 'gust': 6.6}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-30 09:00:00'}, {'dt': 1780142400, 'main': {'temp': 295.85, 'feels_like': 295.27, 'temp_min': 295.85, 'temp_max': 295.85, 'pressure': 1017, 'sea_level': 1017, 'grnd_level': 1012, 'humidity': 42, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 4}, 'wind': {'speed': 5.75, 'deg': 307, 'gust': 7.3}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-30 12:00:00'}, {'dt': 1780153200, 'main': {'temp': 296.51, 'feels_like': 296, 'temp_min': 296.51, 'temp_max': 296.51, 'pressure': 1016, 'sea_level': 1016, 'grnd_level': 1011, 'humidity': 42, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 0}, 'wind': {'speed': 5.29, 'deg': 310, 'gust': 6.87}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-30 15:00:00'}, {'dt': 1780164000, 'main': {'temp': 293.78, 'feels_like': 293.36, 'temp_min': 293.78, 'temp_max': 293.78, 'pressure': 1016, 'sea_level': 1016, 'grnd_level': 1011, 'humidity': 56, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 7}, 'wind': {'speed': 2.78, 'deg': 342, 'gust': 5.19}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-30 18:00:00'}, {'dt': 1780174800, 'main': {'temp': 289.64, 'feels_like': 289.36, 'temp_min': 289.64, 'temp_max': 289.64, 'pressure': 1016, 'sea_level': 1016, 'grnd_level': 1011, 'humidity': 77, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03n'}], 'clouds': {'all': 47}, 'wind': {'speed': 1.8, 'deg': 306, 'gust': 2.91}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-05-30 21:00:00'}, {'dt': 1780185600, 'main': {'temp': 287.7, 'feels_like': 287.51, 'temp_min': 287.7, 'temp_max': 287.7, 'pressure': 1016, 'sea_level': 1016, 'grnd_level': 1010, 'humidity': 88, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04n'}], 'clouds': {'all': 57}, 'wind': {'speed': 2.08, 'deg': 324, 'gust': 3.65}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-05-31 00:00:00'}, {'dt': 1780196400, 'main': {'temp': 286.2, 'feels_like': 285.91, 'temp_min': 286.2, 'temp_max': 286.2, 'pressure': 1015, 'sea_level': 1015, 'grnd_level': 1010, 'humidity': 90, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03d'}], 'clouds': {'all': 38}, 'wind': {'speed': 1.94, 'deg': 308, 'gust': 3.25}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-31 03:00:00'}, {'dt': 1780207200, 'main': {'temp': 289.04, 'feels_like': 288.72, 'temp_min': 289.04, 'temp_max': 289.04, 'pressure': 1015, 'sea_level': 1015, 'grnd_level': 1010, 'humidity': 78, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03d'}], 'clouds': {'all': 42}, 'wind': {'speed': 2.59, 'deg': 290, 'gust': 3.85}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-31 06:00:00'}, {'dt': 1780218000, 'main': {'temp': 293.48, 'feels_like': 292.95, 'temp_min': 293.48, 'temp_max': 293.48, 'pressure': 1014, 'sea_level': 1014, 'grnd_level': 1009, 'humidity': 53, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'clouds': {'all': 51}, 'wind': {'speed': 2.77, 'deg': 287, 'gust': 3.13}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-31 09:00:00'}, {'dt': 1780228800, 'main': {'temp': 295.89, 'feels_like': 295.37, 'temp_min': 295.89, 'temp_max': 295.89, 'pressure': 1013, 'sea_level': 1013, 'grnd_level': 1008, 'humidity': 44, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'clouds': {'all': 76}, 'wind': {'speed': 3.44, 'deg': 292, 'gust': 3.8}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-31 12:00:00'}, {'dt': 1780239600, 'main': {'temp': 296.58, 'feels_like': 296.05, 'temp_min': 296.58, 'temp_max': 296.58, 'pressure': 1012, 'sea_level': 1012, 'grnd_level': 1007, 'humidity': 41, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 100}, 'wind': {'speed': 3.55, 'deg': 311, 'gust': 4.12}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-31 15:00:00'}, {'dt': 1780250400, 'main': {'temp': 293.19, 'feels_like': 292.74, 'temp_min': 293.19, 'temp_max': 293.19, 'pressure': 1012, 'sea_level': 1012, 'grnd_level': 1007, 'humidity': 57, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 98}, 'wind': {'speed': 2.18, 'deg': 321, 'gust': 3.54}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-31 18:00:00'}, {'dt': 1780261200, 'main': {'temp': 290.05, 'feels_like': 289.62, 'temp_min': 290.05, 'temp_max': 290.05, 'pressure': 1013, 'sea_level': 1013, 'grnd_level': 1007, 'humidity': 70, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 99}, 'wind': {'speed': 1.73, 'deg': 326, 'gust': 2.73}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-05-31 21:00:00'}, {'dt': 1780272000, 'main': {'temp': 288.89, 'feels_like': 288.5, 'temp_min': 288.89, 'temp_max': 288.89, 'pressure': 1013, 'sea_level': 1013, 'grnd_level': 1008, 'humidity': 76, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 99}, 'wind': {'speed': 0.4, 'deg': 340, 'gust': 0.59}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-06-01 00:00:00'}, {'dt': 1780282800, 'main': {'temp': 287.83, 'feels_like': 287.55, 'temp_min': 287.83, 'temp_max': 287.83, 'pressure': 1013, 'sea_level': 1013, 'grnd_level': 1008, 'humidity': 84, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 100}, 'wind': {'speed': 1.45, 'deg': 303, 'gust': 2.17}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-01 03:00:00'}, {'dt': 1780293600, 'main': {'temp': 290.36, 'feels_like': 290.02, 'temp_min': 290.36, 'temp_max': 290.36, 'pressure': 1014, 'sea_level': 1014, 'grnd_level': 1009, 'humidity': 72, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 100}, 'wind': {'speed': 1.92, 'deg': 334, 'gust': 2.91}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-01 06:00:00'}, {'dt': 1780304400, 'main': {'temp': 293.65, 'feels_like': 293.24, 'temp_min': 293.65, 'temp_max': 293.65, 'pressure': 1014, 'sea_level': 1014, 'grnd_level': 1009, 'humidity': 57, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 99}, 'wind': {'speed': 3.39, 'deg': 301, 'gust': 4.4}, 'visibility': 10000, 'pop': 0.2, 'rain': {'3h': 0.18}, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-01 09:00:00'}, {'dt': 1780315200, 'main': {'temp': 295.95, 'feels_like': 295.43, 'temp_min': 295.95, 'temp_max': 295.95, 'pressure': 1014, 'sea_level': 1014, 'grnd_level': 1009, 'humidity': 44, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 92}, 'wind': {'speed': 4.16, 'deg': 295, 'gust': 4.99}, 'visibility': 10000, 'pop': 0.2, 'rain': {'3h': 0.18}, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-01 12:00:00'}, {'dt': 1780326000, 'main': {'temp': 293.41, 'feels_like': 292.95, 'temp_min': 293.41, 'temp_max': 293.41, 'pressure': 1014, 'sea_level': 1014, 'grnd_level': 1009, 'humidity': 56, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 99}, 'wind': {'speed': 3.56, 'deg': 287, 'gust': 4.81}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-01 15:00:00'}, {'dt': 1780336800, 'main': {'temp': 293.4, 'feels_like': 292.86, 'temp_min': 293.4, 'temp_max': 293.4, 'pressure': 1013, 'sea_level': 1013, 'grnd_level': 1008, 'humidity': 53, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'clouds': {'all': 75}, 'wind': {'speed': 1.94, 'deg': 301, 'gust': 3.28}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-01 18:00:00'}, {'dt': 1780347600, 'main': {'temp': 289.23, 'feels_like': 288.85, 'temp_min': 289.23, 'temp_max': 289.23, 'pressure': 1014, 'sea_level': 1014, 'grnd_level': 1009, 'humidity': 75, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04n'}], 'clouds': {'all': 80}, 'wind': {'speed': 1.6, 'deg': 286, 'gust': 2.34}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-06-01 21:00:00'}, {'dt': 1780358400, 'main': {'temp': 288.19, 'feels_like': 287.79, 'temp_min': 288.19, 'temp_max': 288.19, 'pressure': 1013, 'sea_level': 1013, 'grnd_level': 1008, 'humidity': 78, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 90}, 'wind': {'speed': 0.86, 'deg': 291, 'gust': 0.87}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-06-02 00:00:00'}, {'dt': 1780369200, 'main': {'temp': 287.59, 'feels_like': 287.15, 'temp_min': 287.59, 'temp_max': 287.59, 'pressure': 1013, 'sea_level': 1013, 'grnd_level': 1007, 'humidity': 79, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 100}, 'wind': {'speed': 1.01, 'deg': 204, 'gust': 1.02}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-02 03:00:00'}, {'dt': 1780380000, 'main': {'temp': 291.55, 'feels_like': 291.06, 'temp_min': 291.55, 'temp_max': 291.55, 'pressure': 1012, 'sea_level': 1012, 'grnd_level': 1007, 'humidity': 62, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'clouds': {'all': 84}, 'wind': {'speed': 2.04, 'deg': 160, 'gust': 2.92}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-02 06:00:00'}, {'dt': 1780390800, 'main': {'temp': 295.34, 'feels_like': 294.84, 'temp_min': 295.34, 'temp_max': 295.34, 'pressure': 1011, 'sea_level': 1011, 'grnd_level': 1006, 'humidity': 47, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 100}, 'wind': {'speed': 2.85, 'deg': 166, 'gust': 3.51}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-02 09:00:00'}], 'city': {'id': 2922467, 'name': 'Gartenfeld', 'coord': {'lat': 52.52, 'lon': 13.24}, 'country': 'DE', 'population': 0, 'timezone': 7200, 'sunrise': 1779936860, 'sunset': 1779995676}}

In [3]:
json.keys()

dict_keys(['cod', 'message', 'cnt', 'list', 'city'])

In [4]:
json['cod']

'200'

In [5]:
json['message']

0

In [6]:
json['cnt']

40

In [7]:
json['list']

[{'dt': 1779894000,
  'main': {'temp': 296.57,
   'feels_like': 295.88,
   'temp_min': 295,
   'temp_max': 296.57,
   'pressure': 1023,
   'sea_level': 1023,
   'grnd_level': 1017,
   'humidity': 35,
   'temp_kf': 1.57},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01d'}],
  'clouds': {'all': 6},
  'wind': {'speed': 5.79, 'deg': 314, 'gust': 6.61},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-27 15:00:00'},
 {'dt': 1779904800,
  'main': {'temp': 295.4,
   'feels_like': 294.67,
   'temp_min': 293.07,
   'temp_max': 295.4,
   'pressure': 1023,
   'sea_level': 1023,
   'grnd_level': 1018,
   'humidity': 38,
   'temp_kf': 2.33},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01d'}],
  'clouds': {'all': 5},
  'wind': {'speed': 5.1, 'deg': 321, 'gust': 6.49},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-27 18:00:00'},
 {'dt': 1779915600,
  'main': {'temp': 289.94,
   'feels_like': 289.11,
   'temp_min': 286.62,
   'temp_max': 289.94,
   'pressure': 1024,
   'sea_level': 1024,
   'grnd_level': 1019,
   'humidity': 55,
   'temp_kf': 3.32},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'clouds': {'all': 4},
  'wind': {'speed': 2.66, 'deg': 328, 'gust': 5.6},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-05-27 21:00:00'},
 {'dt': 1779926400,
  'main': {'temp': 285.98,
   'feels_like': 285.22,
   'temp_min': 285.98,
   'temp_max': 285.98,
   'pressure': 1025,
   'sea_level': 1025,
   'grnd_level': 1019,
   'humidity': 73,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'clouds': {'all': 5},
  'wind': {'speed': 2.66, 'deg': 311, 'gust': 5.93},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-05-28 00:00:00'},
 {'dt': 1779937200,
  'main': {'temp': 283.75,
   'feels_like': 283.14,
   'temp_min': 283.75,
   'temp_max': 283.75,
   'pressure': 1025,
   'sea_level': 1025,
   'grnd_level': 1019,
   'humidity': 87,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01d'}],
  'clouds': {'all': 6},
  'wind': {'speed': 2.59, 'deg': 303, 'gust': 5.57},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-28 03:00:00'},
 {'dt': 1779948000,
  'main': {'temp': 285.74,
   'feels_like': 284.75,
   'temp_min': 285.74,
   'temp_max': 285.74,
   'pressure': 1025,
   'sea_level': 1025,
   'grnd_level': 1020,
   'humidity': 65,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01d'}],
  'clouds': {'all': 6},
  'wind': {'speed': 3.21, 'deg': 296, 'gust': 4.79},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-28 06:00:00'},
 {'dt': 1779958800,
  'main': {'temp': 289.84,
   'feels_like': 288.64,
   'temp_min': 289.84,
   'temp_max': 289.84,
   'pressure': 1025,
   'sea_level': 1025,
   'grnd_level': 1020,
   'humidity': 41,
   'temp_kf': 0},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02d'}],
  'clouds': {'all': 11},
  'wind': {'speed': 3.8, 'deg': 295, 'gust': 4.63},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-28 09:00:00'},
 {'dt': 1779969600,
  'main': {'temp': 292.89,
   'feels_like': 291.78,
   'temp_min': 292.89,
   'temp_max': 292.89,
   'pressure': 1024,
   'sea_level': 1024,
   'grnd_level': 1019,
   'humidity': 33,
   'temp_kf': 0},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02d'}],
  'clouds': {'all': 12},
  'wind': {'speed': 4.46, 'deg': 301, 'gust': 4.91},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-28 12:00:00'},
 {'dt': 1779980400,
  'main': {'temp': 293.44,
   'feels_like': 292.39,
   'temp_min': 293.44,
   'temp_max': 293.44,
   'pressure': 1024,
   'sea_level': 1024,
   'grnd_level': 1019,
   'humidity': 33,
   'temp_kf': 0},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02d'}],
  'clouds': {'all': 14},
  'wind': {'speed': 4.55, 'deg': 305, 'gust': 5.01},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-28 15:00:00'},
 {'dt': 1779991200,
  'main': {'temp': 291.04,
   'feels_like': 290.11,
   'temp_min': 291.04,
   'temp_max': 291.04,
   'pressure': 1024,
   'sea_level': 1024,
   'grnd_level': 1018,
   'humidity': 47,
   'temp_kf': 0},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02d'}],
  'clouds': {'all': 14},
  'wind': {'speed': 3.02, 'deg': 305, 'gust': 4.46},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-28 18:00:00'},
 {'dt': 1780002000,
  'main': {'temp': 286.95,
   'feels_like': 286.06,
   'temp_min': 286.95,
   'temp_max': 286.95,
   'pressure': 1024,
   'sea_level': 1024,
   'grnd_level': 1019,
   'humidity': 64,
   'temp_kf': 0},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02n'}],
  'clouds': {'all': 15},
  'wind': {'speed': 1.46, 'deg': 360, 'gust': 2.01},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-05-28 21:00:00'},
 {'dt': 1780012800,
  'main': {'temp': 285.5,
   'feels_like': 284.59,
   'temp_min': 285.5,
   'temp_max': 285.5,
   'pressure': 1024,
   'sea_level': 1024,
   'grnd_level': 1019,
   'humidity': 69,
   'temp_kf': 0},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03n'}],
  'clouds': {'all': 29},
  'wind': {'speed': 0.97, 'deg': 266, 'gust': 0.9},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-05-29 00:00:00'},
 {'dt': 1780023600,
  'main': {'temp': 284.14,
   'feels_like': 283.2,
   'temp_min': 284.14,
   'temp_max': 284.14,
   'pressure': 1024,
   'sea_level': 1024,
   'grnd_level': 1019,
   'humidity': 73,
   'temp_kf': 0},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03d'}],
  'clouds': {'all': 31},
  'wind': {'speed': 1.38, 'deg': 254, 'gust': 1.68},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-29 03:00:00'},
 {'dt': 1780034400,
  'main': {'temp': 288.35,
   'feels_like': 287.44,
   'temp_min': 288.35,
   'temp_max': 288.35,
   'pressure': 1024,
   'sea_level': 1024,
   'grnd_level': 1019,
   'humidity': 58,
   'temp_kf': 0},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02d'}],
  'clouds': {'all': 23},
  'wind': {'speed': 2.06, 'deg': 243, 'gust': 3.23},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-29 06:00:00'},
 {'dt': 1780045200,
  'main': {'temp': 294,
   'feels_like': 293.16,
   'temp_min': 294,
   'temp_max': 294,
   'pressure': 1023,
   'sea_level': 1023,
   'grnd_level': 1018,
   'humidity': 39,
   'temp_kf': 0},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02d'}],
  'clouds': {'all': 16},
  'wind': {'speed': 2.84, 'deg': 258, 'gust': 3.68},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-29 09:00:00'},
 {'dt': 1780056000,
  'main': {'temp': 297.39,
   'feels_like': 296.6,
   'temp_min': 297.39,
   'temp_max': 297.39,
   'pressure': 1022,
   'sea_level': 1022,
   'grnd_level': 1017,
   'humidity': 28,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01d'}],
  'clouds': {'all': 10},
  'wind': {'speed': 3.64, 'deg': 292, 'gust': 4.27},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-29 12:00:00'},
 {'dt': 1780066800,
  'main': {'temp': 298.08,
   'feels_like': 297.39,
   'temp_min': 298.08,
   'temp_max': 298.08,
   'pressure': 1021,
   'sea_level': 1021,
   'grnd_level': 1016,
   'humidity': 29,
   'temp_kf': 0},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03d'}],
  'clouds': {'all': 37},
  'wind': {'speed': 3.81, 'deg': 303, 'gust': 5.02},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-29 15:00:00'},
 {'dt': 1780077600,
  'main': {'temp': 294.37,
   'feels_like': 293.83,
   'temp_min': 294.37,
   'temp_max': 294.37,
   'pressure': 1020,
   'sea_level': 1020,
   'grnd_level': 1015,
   'humidity': 49,
   'temp_kf': 0},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04d'}],
  'clouds': {'all': 68},
  'wind': {'speed': 1.81, 'deg': 328, 'gust': 2.96},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-29 18:00:00'},
 {'dt': 1780088400,
  'main': {'temp': 291.64,
   'feels_like': 291.14,
   'temp_min': 291.64,
   'temp_max': 291.64,
   'pressure': 1020,
   'sea_level': 1020,
   'grnd_level': 1014,
   'humidity': 61,
   'temp_kf': 0},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04n'}],
  'clouds': {'all': 99},
  'wind': {'speed': 2.5, 'deg': 244, 'gust': 5.46},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-05-29 21:00:00'},
 {'dt': 1780099200,
  'main': {'temp': 289.76,
   'feels_like': 289.96,
   'temp_min': 289.76,
   'temp_max': 289.76,
   'pressure': 1019,
   'sea_level': 1019,
   'grnd_level': 1014,
   'humidity': 95,
   'temp_kf': 0},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'light rain',
    'icon': '10n'}],
  'clouds': {'all': 100},
  'wind': {'speed': 2.44, 'deg': 277, 'gust': 8.55},
  'visibility': 10000,
  'pop': 1,
  'rain': {'3h': 2.16},
  'sys': {'pod': 'n'},
  'dt_txt': '2026-05-30 00:00:00'},
 {'dt': 1780110000,
  'main': {'temp': 289.38,
   'feels_like': 289.59,
   'temp_min': 289.38,
   'temp_max': 289.38,
   'pressure': 1018,
   'sea_level': 1018,
   'grnd_level': 1012,
   'humidity': 97,
   'temp_kf': 0},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'light rain',
    'icon': '10d'}],
  'clouds': {'all': 100},
  'wind': {'speed': 2.43, 'deg': 250, 'gust': 5.97},
  'visibility': 10000,
  'pop': 1,
  'rain': {'3h': 1.28},
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-30 03:00:00'},
 {'dt': 1780120800,
  'main': {'temp': 290.22,
   'feels_like': 290.15,
   'temp_min': 290.22,
   'temp_max': 290.22,
   'pressure': 1017,
   'sea_level': 1017,
   'grnd_level': 1012,
   'humidity': 83,
   'temp_kf': 0},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'light rain',
    'icon': '10d'}],
  'clouds': {'all': 90},
  'wind': {'speed': 4.59, 'deg': 301, 'gust': 8.01},
  'visibility': 10000,
  'pop': 1,
  'rain': {'3h': 1.46},
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-30 06:00:00'},
 {'dt': 1780131600,
  'main': {'temp': 293.24,
   'feels_like': 292.64,
   'temp_min': 293.24,
   'temp_max': 293.24,
   'pressure': 1017,
   'sea_level': 1017,
   'grnd_level': 1012,
   'humidity': 51,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01d'}],
  'clouds': {'all': 4},
  'wind': {'speed': 5.74, 'deg': 303, 'gust': 7.82},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-30 09:00:00'},
 {'dt': 1780142400,
  'main': {'temp': 295.87,
   'feels_like': 295.37,
   'temp_min': 295.87,
   'temp_max': 295.87,
   'pressure': 1016,
   'sea_level': 1016,
   'grnd_level': 1011,
   'humidity': 45,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01d'}],
  'clouds': {'all': 6},
  'wind': {'speed': 5.91, 'deg': 307, 'gust': 7.78},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-30 12:00:00'},
 {'dt': 1780153200,
  'main': {'temp': 294.81,
   'feels_like': 294.36,
   'temp_min': 294.81,
   'temp_max': 294.81,
   'pressure': 1016,
   'sea_level': 1016,
   'grnd_level': 1011,
   'humidity': 51,
   'temp_kf': 0},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03d'}],
  'clouds': {'all': 29},
  'wind': {'speed': 5.23, 'deg': 317, 'gust': 7.83},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-30 15:00:00'},
 {'dt': 1780164000,
  'main': {'temp': 293.17,
   'feels_like': 292.82,
   'temp_min': 293.17,
   'temp_max': 293.17,
   'pressure': 1015,
   'sea_level': 1015,
   'grnd_level': 1010,
   'humidity': 61,
   'temp_kf': 0},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04d'}],
  'clouds': {'all': 52},
  'wind': {'speed': 3.43, 'deg': 325, 'gust': 6.29},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-30 18:00:00'},
 {'dt': 1780174800,
  'main': {'temp': 289.13,
   'feels_like': 288.92,
   'temp_min': 289.13,
   'temp_max': 289.13,
   'pressure': 1015,
   'sea_level': 1015,
   'grnd_level': 1010,
   'humidity': 82,
   'temp_kf': 0},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03n'}],
  'clouds': {'all': 31},
  'wind': {'speed': 1.82, 'deg': 342, 'gust': 3.46},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-05-30 21:00:00'},
 {'dt': 1780185600,
  'main': {'temp': 287.62,
   'feels_like': 287.39,
   'temp_min': 287.62,
   'temp_max': 287.62,
   'pressure': 1014,
   'sea_level': 1014,
   'grnd_level': 1009,
   'humidity': 87,
   'temp_kf': 0},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03n'}],
  'clouds': {'all': 31},
  'wind': {'speed': 1.01, 'deg': 288, 'gust': 0.98},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-05-31 00:00:00'},
 {'dt': 1780196400,
  'main': {'temp': 286.39,
   'feels_like': 286.15,
   'temp_min': 286.39,
   'temp_max': 286.39,
   'pressure': 1013,
   'sea_level': 1013,
   'grnd_level': 1008,
   'humidity': 91,
   'temp_kf': 0},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02d'}],
  'clouds': {'all': 16},
  'wind': {'speed': 1.44, 'deg': 258, 'gust': 1.98},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-31 03:00:00'},
 {'dt': 1780207200,
  'main': {'temp': 289.59,
   'feels_like': 289.2,
   'temp_min': 289.59,
   'temp_max': 289.59,
   'pressure': 1013,
   'sea_level': 1013,
   'grnd_level': 1008,
   'humidity': 73,
   'temp_kf': 0},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03d'}],
  'clouds': {'all': 41},
  'wind': {'speed': 2.15, 'deg': 283, 'gust': 3.19},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-31 06:00:00'},
 {'dt': 1780218000,
  'main': {'temp': 294.29,
   'feels_like': 293.79,
   'temp_min': 294.29,
   'temp_max': 294.29,
   'pressure': 1012,
   'sea_level': 1012,
   'grnd_level': 1006,
   'humidity': 51,
   'temp_kf': 0},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03d'}],
  'clouds': {'all': 39},
  'wind': {'speed': 2.46, 'deg': 280, 'gust': 3.45},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-31 09:00:00'},
 {'dt': 1780228800,
  'main': {'temp': 294.42,
   'feels_like': 293.99,
   'temp_min': 294.42,
   'temp_max': 294.42,
   'pressure': 1011,
   'sea_level': 1011,
   'grnd_level': 1006,
   'humidity': 53,
   'temp_kf': 0},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04d'}],
  'clouds': {'all': 55},
  'wind': {'speed': 4.03, 'deg': 295, 'gust': 4.2},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-31 12:00:00'},
 {'dt': 1780239600,
  'main': {'temp': 293.32,
   'feels_like': 293.04,
   'temp_min': 293.32,
   'temp_max': 293.32,
   'pressure': 1010,
   'sea_level': 1010,
   'grnd_level': 1005,
   'humidity': 63,
   'temp_kf': 0},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'light rain',
    'icon': '10d'}],
  'clouds': {'all': 91},
  'wind': {'speed': 2.5, 'deg': 278, 'gust': 3.18},
  'visibility': 10000,
  'pop': 1,
  'rain': {'3h': 0.71},
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-31 15:00:00'},
 {'dt': 1780250400,
  'main': {'temp': 291.68,
   'feels_like': 291.6,
   'temp_min': 291.68,
   'temp_max': 291.68,
   'pressure': 1010,
   'sea_level': 1010,
   'grnd_level': 1004,
   'humidity': 77,
   'temp_kf': 0},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'light rain',
    'icon': '10d'}],
  'clouds': {'all': 90},
  'wind': {'speed': 2.3, 'deg': 280, 'gust': 3.59},
  'visibility': 7011,
  'pop': 1,
  'rain': {'3h': 1.43},
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-31 18:00:00'},
 {'dt': 1780261200,
  'main': {'temp': 288.67,
   'feels_like': 288.68,
   'temp_min': 288.67,
   'temp_max': 288.67,
   'pressure': 1010,
   'sea_level': 1010,
   'grnd_level': 1005,
   'humidity': 92,
   'temp_kf': 0},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'light rain',
    'icon': '10n'}],
  'clouds': {'all': 100},
  'wind': {'speed': 2.46, 'deg': 289, 'gust': 5.63},
  'visibility': 10000,
  'pop': 1,
  'rain': {'3h': 1.99},
  'sys': {'pod': 'n'},
  'dt_txt': '2026-05-31 21:00:00'},
 {'dt': 1780272000,
  'main': {'temp': 287.24,
   'feels_like': 287.13,
   'temp_min': 287.24,
   'temp_max': 287.24,
   'pressure': 1011,
   'sea_level': 1011,
   'grnd_level': 1005,
   'humidity': 93,
   'temp_kf': 0},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04n'}],
  'clouds': {'all': 100},
  'wind': {'speed': 2.72, 'deg': 276, 'gust': 7.06},
  'visibility': 10000,
  'pop': 0.8,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-06-01 00:00:00'},
 {'dt': 1780282800,
  'main': {'temp': 285.62,
   'feels_like': 285.46,
   'temp_min': 285.62,
   'temp_max': 285.62,
   'pressure': 1011,
   'sea_level': 1011,
   'grnd_level': 1006,
   'humidity': 97,
   'temp_kf': 0},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04d'}],
  'clouds': {'all': 60},
  'wind': {'speed': 3.62, 'deg': 275, 'gust': 9.1},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-06-01 03:00:00'},
 {'dt': 1780293600,
  'main': {'temp': 287.91,
   'feels_like': 287.61,
   'temp_min': 287.91,
   'temp_max': 287.91,
   'pressure': 1012,
   'sea_level': 1012,
   'grnd_level': 1007,
   'humidity': 83,
   'temp_kf': 0},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04d'}],
  'clouds': {'all': 66},
  'wind': {'speed': 4.51, 'deg': 272, 'gust': 7.75},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-06-01 06:00:00'},
 {'dt': 1780304400,
  'main': {'temp': 291.94,
   'feels_like': 291.39,
   'temp_min': 291.94,
   'temp_max': 291.94,
   'pressure': 1012,
   'sea_level': 1012,
   'grnd_level': 1007,
   'humidity': 58,
   'temp_kf': 0},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'clouds': {'all': 100},
  'wind': {'speed': 4.46, 'deg': 271, 'gust': 6.51},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-06-01 09:00:00'},
 {'dt': 1780315200,
  'main': {'temp': 293.08,
   'feels_like': 292.7,
   'temp_min': 293.08,
   'temp_max': 293.08,
   'pressure': 1012,
   'sea_level': 1012,
   'grnd_level': 1006,
   'humidity': 60,
   'temp_kf': 0},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'light rain',
    'icon': '10d'}],
  'clouds': {'all': 98},
  'wind': {'speed': 5.09, 'deg': 262, 'gust': 6.94},
  'visibility': 10000,
  'pop': 1,
  'rain': {'3h': 0.78},
  'sys': {'pod': 'd'},
  'dt_txt': '2026-06-01 12:00:00'}]

In [8]:
json['city']

{'id': 2922467,
 'name': 'Gartenfeld',
 'coord': {'lat': 52.52, 'lon': 13.24},
 'country': 'DE',
 'population': 0,
 'timezone': 7200,
 'sunrise': 1779850523,
 'sunset': 1779909198}

## Hamburg

In [ ]:
latitude = 53.55
longitude = 10.00
API_key = os.getenv("OPENWEATHER_API_KEY")

url = f"https://api.openweathermap.org/data/2.5/forecast?lat={latitude}&lon={longitude}&appid={API_key}"

response = requests.get(url)
json = response.json()

print(json)

{'cod': '200', 'message': 0, 'cnt': 40, 'list': [{'dt': 1779894000, 'main': {'temp': 292.78, 'feels_like': 292, 'temp_min': 292.53, 'temp_max': 292.78, 'pressure': 1025, 'sea_level': 1025, 'grnd_level': 1023, 'humidity': 46, 'temp_kf': 0.25}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 0}, 'wind': {'speed': 5.15, 'deg': 316, 'gust': 6.1}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-27 15:00:00'}, {'dt': 1779904800, 'main': {'temp': 291.4, 'feels_like': 290.56, 'temp_min': 288.64, 'temp_max': 291.4, 'pressure': 1025, 'sea_level': 1025, 'grnd_level': 1023, 'humidity': 49, 'temp_kf': 2.76}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 1}, 'wind': {'speed': 4.27, 'deg': 317, 'gust': 7.23}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-27 18:00:00'}, {'dt': 1779915600, 'main': {'temp': 286.85, 'feels_like': 286.18, 'temp_min': 283.89, 'temp_max': 286.85, 'pressure': 1026, 'sea_level': 1026, 'grnd_level': 1024, 'humidity': 73, 'temp_kf': 2.96}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'clouds': {'all': 0}, 'wind': {'speed': 2.53, 'deg': 305, 'gust': 7.57}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-05-27 21:00:00'}, {'dt': 1779926400, 'main': {'temp': 281.49, 'feels_like': 280.24, 'temp_min': 281.49, 'temp_max': 281.49, 'pressure': 1026, 'sea_level': 1026, 'grnd_level': 1024, 'humidity': 95, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'clouds': {'all': 2}, 'wind': {'speed': 2.2, 'deg': 298, 'gust': 4.85}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-05-28 00:00:00'}, {'dt': 1779937200, 'main': {'temp': 280.09, 'feels_like': 278.69, 'temp_min': 280.09, 'temp_max': 280.09, 'pressure': 1026, 'sea_level': 1026, 'grnd_level': 1023, 'humidity': 96, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'clouds': {'all': 7}, 'wind': {'speed': 2.1, 'deg': 285, 'gust': 3.57}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-05-28 03:00:00'}, {'dt': 1779948000, 'main': {'temp': 284.28, 'feels_like': 283.28, 'temp_min': 284.28, 'temp_max': 284.28, 'pressure': 1026, 'sea_level': 1026, 'grnd_level': 1024, 'humidity': 70, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 10}, 'wind': {'speed': 2.72, 'deg': 306, 'gust': 5.4}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-28 06:00:00'}, {'dt': 1779958800, 'main': {'temp': 290.17, 'feels_like': 289.1, 'temp_min': 290.17, 'temp_max': 290.17, 'pressure': 1026, 'sea_level': 1026, 'grnd_level': 1023, 'humidity': 45, 'temp_kf': 0}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02d'}], 'clouds': {'all': 15}, 'wind': {'speed': 3.12, 'deg': 302, 'gust': 4.23}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-28 09:00:00'}, {'dt': 1779969600, 'main': {'temp': 292.88, 'feels_like': 291.9, 'temp_min': 292.88, 'temp_max': 292.88, 'pressure': 1025, 'sea_level': 1025, 'grnd_level': 1023, 'humidity': 38, 'temp_kf': 0}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02d'}], 'clouds': {'all': 13}, 'wind': {'speed': 4.19, 'deg': 300, 'gust': 4.7}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-28 12:00:00'}, {'dt': 1779980400, 'main': {'temp': 292.41, 'feels_like': 291.44, 'temp_min': 292.41, 'temp_max': 292.41, 'pressure': 1025, 'sea_level': 1025, 'grnd_level': 1022, 'humidity': 40, 'temp_kf': 0}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02d'}], 'clouds': {'all': 12}, 'wind': {'speed': 3.91, 'deg': 306, 'gust': 4.18}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-28 15:00:00'}, {'dt': 1779991200, 'main': {'temp': 288.76, 'feels_like': 287.94, 'temp_min': 288.76, 'temp_max': 288.76, 'pressure': 1024, 'sea_level': 1024, 'grnd_level': 1022, 'humidity': 60, 'temp_kf': 0}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02d'}], 'clouds': {'all': 12}, 'wind': {'speed': 2.78, 'deg': 297, 'gust': 5.05}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-28 18:00:00'}, {'dt': 1780002000, 'main': {'temp': 282.19, 'feels_like': 281.54, 'temp_min': 282.19, 'temp_max': 282.19, 'pressure': 1025, 'sea_level': 1025, 'grnd_level': 1022, 'humidity': 86, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'clouds': {'all': 10}, 'wind': {'speed': 1.66, 'deg': 309, 'gust': 1.67}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-05-28 21:00:00'}, {'dt': 1780012800, 'main': {'temp': 280.86, 'feels_like': 280.86, 'temp_min': 280.86, 'temp_max': 280.86, 'pressure': 1024, 'sea_level': 1024, 'grnd_level': 1022, 'humidity': 86, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03n'}], 'clouds': {'all': 28}, 'wind': {'speed': 0.77, 'deg': 280, 'gust': 0.76}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-05-29 00:00:00'}, {'dt': 1780023600, 'main': {'temp': 280.08, 'feels_like': 280.08, 'temp_min': 280.08, 'temp_max': 280.08, 'pressure': 1024, 'sea_level': 1024, 'grnd_level': 1021, 'humidity': 81, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04n'}], 'clouds': {'all': 63}, 'wind': {'speed': 1.12, 'deg': 182, 'gust': 1.11}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-05-29 03:00:00'}, {'dt': 1780034400, 'main': {'temp': 286.76, 'feels_like': 285.51, 'temp_min': 286.76, 'temp_max': 286.76, 'pressure': 1024, 'sea_level': 1024, 'grnd_level': 1021, 'humidity': 51, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03d'}], 'clouds': {'all': 33}, 'wind': {'speed': 1.32, 'deg': 180, 'gust': 2.04}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-29 06:00:00'}, {'dt': 1780045200, 'main': {'temp': 294.07, 'feels_like': 293.16, 'temp_min': 294.07, 'temp_max': 294.07, 'pressure': 1023, 'sea_level': 1023, 'grnd_level': 1020, 'humidity': 36, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03d'}], 'clouds': {'all': 26}, 'wind': {'speed': 2.02, 'deg': 209, 'gust': 3.27}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-29 09:00:00'}, {'dt': 1780056000, 'main': {'temp': 297.72, 'feels_like': 297.2, 'temp_min': 297.72, 'temp_max': 297.72, 'pressure': 1021, 'sea_level': 1021, 'grnd_level': 1019, 'humidity': 37, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 36}, 'wind': {'speed': 2.9, 'deg': 234, 'gust': 3.92}, 'visibility': 10000, 'pop': 0.2, 'rain': {'3h': 0.1}, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-29 12:00:00'}, {'dt': 1780066800, 'main': {'temp': 295.97, 'feels_like': 295.87, 'temp_min': 295.97, 'temp_max': 295.97, 'pressure': 1020, 'sea_level': 1020, 'grnd_level': 1018, 'humidity': 60, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 100}, 'wind': {'speed': 3.62, 'deg': 246, 'gust': 5.91}, 'visibility': 10000, 'pop': 0.27, 'rain': {'3h': 0.18}, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-29 15:00:00'}, {'dt': 1780077600, 'main': {'temp': 293.62, 'feels_like': 293.89, 'temp_min': 293.62, 'temp_max': 293.62, 'pressure': 1019, 'sea_level': 1019, 'grnd_level': 1017, 'humidity': 83, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 100}, 'wind': {'speed': 2.1, 'deg': 223, 'gust': 4.96}, 'visibility': 10000, 'pop': 0.2, 'rain': {'3h': 0.35}, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-29 18:00:00'}, {'dt': 1780088400, 'main': {'temp': 289.32, 'feels_like': 289.53, 'temp_min': 289.32, 'temp_max': 289.32, 'pressure': 1019, 'sea_level': 1019, 'grnd_level': 1017, 'humidity': 97, 'temp_kf': 0}, 'weather': [{'id': 501, 'main': 'Rain', 'description': 'moderate rain', 'icon': '10n'}], 'clouds': {'all': 100}, 'wind': {'speed': 2.47, 'deg': 278, 'gust': 4.75}, 'visibility': 2997, 'pop': 1, 'rain': {'3h': 4.48}, 'sys': {'pod': 'n'}, 'dt_txt': '2026-05-29 21:00:00'}, {'dt': 1780099200, 'main': {'temp': 285.43, 'feels_like': 285.25, 'temp_min': 285.43, 'temp_max': 285.43, 'pressure': 1019, 'sea_level': 1019, 'grnd_level': 1016, 'humidity': 97, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10n'}], 'clouds': {'all': 99}, 'wind': {'speed': 2.57, 'deg': 284, 'gust': 8.05}, 'visibility': 10000, 'pop': 1, 'rain': {'3h': 0.8}, 'sys': {'pod': 'n'}, 'dt_txt': '2026-05-30 00:00:00'}, {'dt': 1780110000, 'main': {'temp': 283.5, 'feels_like': 283.15, 'temp_min': 283.5, 'temp_max': 283.5, 'pressure': 1019, 'sea_level': 1019, 'grnd_level': 1016, 'humidity': 98, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 9}, 'wind': {'speed': 2.62, 'deg': 281, 'gust': 8.95}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-30 03:00:00'}, {'dt': 1780120800, 'main': {'temp': 287.27, 'feels_like': 287.09, 'temp_min': 287.27, 'temp_max': 287.27, 'pressure': 1019, 'sea_level': 1019, 'grnd_level': 1017, 'humidity': 90, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 10}, 'wind': {'speed': 3.43, 'deg': 289, 'gust': 8.38}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-30 06:00:00'}, {'dt': 1780131600, 'main': {'temp': 292.92, 'feels_like': 292.44, 'temp_min': 292.92, 'temp_max': 292.92, 'pressure': 1018, 'sea_level': 1018, 'grnd_level': 1016, 'humidity': 57, 'temp_kf': 0}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02d'}], 'clouds': {'all': 21}, 'wind': {'speed': 5.41, 'deg': 295, 'gust': 7.96}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-30 09:00:00'}, {'dt': 1780142400, 'main': {'temp': 294.17, 'feels_like': 293.66, 'temp_min': 294.17, 'temp_max': 294.17, 'pressure': 1018, 'sea_level': 1018, 'grnd_level': 1016, 'humidity': 51, 'temp_kf': 0}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02d'}], 'clouds': {'all': 15}, 'wind': {'speed': 5.78, 'deg': 300, 'gust': 7.93}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-30 12:00:00'}, {'dt': 1780153200, 'main': {'temp': 293.48, 'feels_like': 292.93, 'temp_min': 293.48, 'temp_max': 293.48, 'pressure': 1017, 'sea_level': 1017, 'grnd_level': 1015, 'humidity': 52, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03d'}], 'clouds': {'all': 27}, 'wind': {'speed': 5.22, 'deg': 301, 'gust': 6.78}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-30 15:00:00'}, {'dt': 1780164000, 'main': {'temp': 290.01, 'feels_like': 289.55, 'temp_min': 290.01, 'temp_max': 290.01, 'pressure': 1017, 'sea_level': 1017, 'grnd_level': 1014, 'humidity': 69, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03d'}], 'clouds': {'all': 36}, 'wind': {'speed': 3.34, 'deg': 294, 'gust': 5.91}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-30 18:00:00'}, {'dt': 1780174800, 'main': {'temp': 284.51, 'feels_like': 284.16, 'temp_min': 284.51, 'temp_max': 284.51, 'pressure': 1016, 'sea_level': 1016, 'grnd_level': 1013, 'humidity': 94, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03n'}], 'clouds': {'all': 34}, 'wind': {'speed': 1.96, 'deg': 296, 'gust': 2.74}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-05-30 21:00:00'}, {'dt': 1780185600, 'main': {'temp': 283.05, 'feels_like': 283.05, 'temp_min': 283.05, 'temp_max': 283.05, 'pressure': 1014, 'sea_level': 1014, 'grnd_level': 1012, 'humidity': 94, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03n'}], 'clouds': {'all': 28}, 'wind': {'speed': 1.1, 'deg': 280, 'gust': 1.1}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-05-31 00:00:00'}, {'dt': 1780196400, 'main': {'temp': 282.37, 'feels_like': 282.37, 'temp_min': 282.37, 'temp_max': 282.37, 'pressure': 1013, 'sea_level': 1013, 'grnd_level': 1011, 'humidity': 94, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'clouds': {'all': 57}, 'wind': {'speed': 1.2, 'deg': 288, 'gust': 1.17}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-31 03:00:00'}, {'dt': 1780207200, 'main': {'temp': 287.89, 'feels_like': 287.3, 'temp_min': 287.89, 'temp_max': 287.89, 'pressure': 1012, 'sea_level': 1012, 'grnd_level': 1010, 'humidity': 72, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'clouds': {'all': 57}, 'wind': {'speed': 1.31, 'deg': 272, 'gust': 2.37}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-31 06:00:00'}, {'dt': 1780218000, 'main': {'temp': 290.12, 'feels_like': 289.65, 'temp_min': 290.12, 'temp_max': 290.12, 'pressure': 1012, 'sea_level': 1012, 'grnd_level': 1009, 'humidity': 68, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 100}, 'wind': {'speed': 2.32, 'deg': 260, 'gust': 3.44}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-31 09:00:00'}, {'dt': 1780228800, 'main': {'temp': 293.31, 'feels_like': 293.05, 'temp_min': 293.31, 'temp_max': 293.31, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 1008, 'humidity': 64, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 96}, 'wind': {'speed': 3.26, 'deg': 283, 'gust': 4.71}, 'visibility': 10000, 'pop': 0.28, 'rain': {'3h': 0.5}, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-31 12:00:00'}, {'dt': 1780239600, 'main': {'temp': 293.62, 'feels_like': 293.18, 'temp_min': 293.62, 'temp_max': 293.62, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 1008, 'humidity': 56, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 46}, 'wind': {'speed': 4.57, 'deg': 313, 'gust': 5.58}, 'visibility': 10000, 'pop': 0.85, 'rain': {'3h': 0.83}, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-31 15:00:00'}, {'dt': 1780250400, 'main': {'temp': 290.29, 'feels_like': 289.78, 'temp_min': 290.29, 'temp_max': 290.29, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 1008, 'humidity': 66, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'clouds': {'all': 54}, 'wind': {'speed': 2.99, 'deg': 301, 'gust': 5.85}, 'visibility': 10000, 'pop': 0.56, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-31 18:00:00'}, {'dt': 1780261200, 'main': {'temp': 285.56, 'feels_like': 285.21, 'temp_min': 285.56, 'temp_max': 285.56, 'pressure': 1011, 'sea_level': 1011, 'grnd_level': 1008, 'humidity': 90, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04n'}], 'clouds': {'all': 77}, 'wind': {'speed': 2.46, 'deg': 269, 'gust': 7.63}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-05-31 21:00:00'}, {'dt': 1780272000, 'main': {'temp': 283.94, 'feels_like': 283.63, 'temp_min': 283.94, 'temp_max': 283.94, 'pressure': 1011, 'sea_level': 1011, 'grnd_level': 1009, 'humidity': 98, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04n'}], 'clouds': {'all': 62}, 'wind': {'speed': 3, 'deg': 249, 'gust': 8.89}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-06-01 00:00:00'}, {'dt': 1780282800, 'main': {'temp': 283.01, 'feels_like': 281.56, 'temp_min': 283.01, 'temp_max': 283.01, 'pressure': 1011, 'sea_level': 1011, 'grnd_level': 1008, 'humidity': 98, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 88}, 'wind': {'speed': 2.88, 'deg': 240, 'gust': 9.29}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-01 03:00:00'}, {'dt': 1780293600, 'main': {'temp': 287.33, 'feels_like': 286.84, 'temp_min': 287.33, 'temp_max': 287.33, 'pressure': 1011, 'sea_level': 1011, 'grnd_level': 1008, 'humidity': 78, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'clouds': {'all': 75}, 'wind': {'speed': 3.8, 'deg': 239, 'gust': 7.26}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-01 06:00:00'}, {'dt': 1780304400, 'main': {'temp': 288.45, 'feels_like': 288.18, 'temp_min': 288.45, 'temp_max': 288.45, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 1008, 'humidity': 82, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 100}, 'wind': {'speed': 3.76, 'deg': 223, 'gust': 6.99}, 'visibility': 10000, 'pop': 0.33, 'rain': {'3h': 0.21}, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-01 09:00:00'}, {'dt': 1780315200, 'main': {'temp': 291.18, 'feels_like': 291.08, 'temp_min': 291.18, 'temp_max': 291.18, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 1008, 'humidity': 78, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 98}, 'wind': {'speed': 3.94, 'deg': 264, 'gust': 6.12}, 'visibility': 10000, 'pop': 1, 'rain': {'3h': 2.16}, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-01 12:00:00'}], 'city': {'id': 2911298, 'name': 'Hamburg', 'coord': {'lat': 53.55, 'lon': 10}, 'country': 'DE', 'population': 1739117, 'timezone': 7200, 'sunrise': 1779850973, 'sunset': 1779910303}}

## Munich

In [ ]:
latitude = 48.14
longitude = 11.58
API_key = os.getenv("OPENWEATHER_API_KEY")

url = f"https://api.openweathermap.org/data/2.5/forecast?lat={latitude}&lon={longitude}&appid={API_key}"

cresponse = requests.get(url)
json = response.json()

print(json)

{'cod': '200', 'message': 0, 'cnt': 40, 'list': [{'dt': 1779894000, 'main': {'temp': 292.78, 'feels_like': 292, 'temp_min': 292.53, 'temp_max': 292.78, 'pressure': 1025, 'sea_level': 1025, 'grnd_level': 1023, 'humidity': 46, 'temp_kf': 0.25}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 0}, 'wind': {'speed': 5.15, 'deg': 316, 'gust': 6.1}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-27 15:00:00'}, {'dt': 1779904800, 'main': {'temp': 291.4, 'feels_like': 290.56, 'temp_min': 288.64, 'temp_max': 291.4, 'pressure': 1025, 'sea_level': 1025, 'grnd_level': 1023, 'humidity': 49, 'temp_kf': 2.76}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 1}, 'wind': {'speed': 4.27, 'deg': 317, 'gust': 7.23}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-27 18:00:00'}, {'dt': 1779915600, 'main': {'temp': 286.85, 'feels_like': 286.18, 'temp_min': 283.89, 'temp_max': 286.85, 'pressure': 1026, 'sea_level': 1026, 'grnd_level': 1024, 'humidity': 73, 'temp_kf': 2.96}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'clouds': {'all': 0}, 'wind': {'speed': 2.53, 'deg': 305, 'gust': 7.57}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-05-27 21:00:00'}, {'dt': 1779926400, 'main': {'temp': 281.49, 'feels_like': 280.24, 'temp_min': 281.49, 'temp_max': 281.49, 'pressure': 1026, 'sea_level': 1026, 'grnd_level': 1024, 'humidity': 95, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'clouds': {'all': 2}, 'wind': {'speed': 2.2, 'deg': 298, 'gust': 4.85}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-05-28 00:00:00'}, {'dt': 1779937200, 'main': {'temp': 280.09, 'feels_like': 278.69, 'temp_min': 280.09, 'temp_max': 280.09, 'pressure': 1026, 'sea_level': 1026, 'grnd_level': 1023, 'humidity': 96, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'clouds': {'all': 7}, 'wind': {'speed': 2.1, 'deg': 285, 'gust': 3.57}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-05-28 03:00:00'}, {'dt': 1779948000, 'main': {'temp': 284.28, 'feels_like': 283.28, 'temp_min': 284.28, 'temp_max': 284.28, 'pressure': 1026, 'sea_level': 1026, 'grnd_level': 1024, 'humidity': 70, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 10}, 'wind': {'speed': 2.72, 'deg': 306, 'gust': 5.4}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-28 06:00:00'}, {'dt': 1779958800, 'main': {'temp': 290.17, 'feels_like': 289.1, 'temp_min': 290.17, 'temp_max': 290.17, 'pressure': 1026, 'sea_level': 1026, 'grnd_level': 1023, 'humidity': 45, 'temp_kf': 0}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02d'}], 'clouds': {'all': 15}, 'wind': {'speed': 3.12, 'deg': 302, 'gust': 4.23}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-28 09:00:00'}, {'dt': 1779969600, 'main': {'temp': 292.88, 'feels_like': 291.9, 'temp_min': 292.88, 'temp_max': 292.88, 'pressure': 1025, 'sea_level': 1025, 'grnd_level': 1023, 'humidity': 38, 'temp_kf': 0}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02d'}], 'clouds': {'all': 13}, 'wind': {'speed': 4.19, 'deg': 300, 'gust': 4.7}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-28 12:00:00'}, {'dt': 1779980400, 'main': {'temp': 292.41, 'feels_like': 291.44, 'temp_min': 292.41, 'temp_max': 292.41, 'pressure': 1025, 'sea_level': 1025, 'grnd_level': 1022, 'humidity': 40, 'temp_kf': 0}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02d'}], 'clouds': {'all': 12}, 'wind': {'speed': 3.91, 'deg': 306, 'gust': 4.18}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-28 15:00:00'}, {'dt': 1779991200, 'main': {'temp': 288.76, 'feels_like': 287.94, 'temp_min': 288.76, 'temp_max': 288.76, 'pressure': 1024, 'sea_level': 1024, 'grnd_level': 1022, 'humidity': 60, 'temp_kf': 0}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02d'}], 'clouds': {'all': 12}, 'wind': {'speed': 2.78, 'deg': 297, 'gust': 5.05}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-28 18:00:00'}, {'dt': 1780002000, 'main': {'temp': 282.19, 'feels_like': 281.54, 'temp_min': 282.19, 'temp_max': 282.19, 'pressure': 1025, 'sea_level': 1025, 'grnd_level': 1022, 'humidity': 86, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'clouds': {'all': 10}, 'wind': {'speed': 1.66, 'deg': 309, 'gust': 1.67}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-05-28 21:00:00'}, {'dt': 1780012800, 'main': {'temp': 280.86, 'feels_like': 280.86, 'temp_min': 280.86, 'temp_max': 280.86, 'pressure': 1024, 'sea_level': 1024, 'grnd_level': 1022, 'humidity': 86, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03n'}], 'clouds': {'all': 28}, 'wind': {'speed': 0.77, 'deg': 280, 'gust': 0.76}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-05-29 00:00:00'}, {'dt': 1780023600, 'main': {'temp': 280.08, 'feels_like': 280.08, 'temp_min': 280.08, 'temp_max': 280.08, 'pressure': 1024, 'sea_level': 1024, 'grnd_level': 1021, 'humidity': 81, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04n'}], 'clouds': {'all': 63}, 'wind': {'speed': 1.12, 'deg': 182, 'gust': 1.11}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-05-29 03:00:00'}, {'dt': 1780034400, 'main': {'temp': 286.76, 'feels_like': 285.51, 'temp_min': 286.76, 'temp_max': 286.76, 'pressure': 1024, 'sea_level': 1024, 'grnd_level': 1021, 'humidity': 51, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03d'}], 'clouds': {'all': 33}, 'wind': {'speed': 1.32, 'deg': 180, 'gust': 2.04}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-29 06:00:00'}, {'dt': 1780045200, 'main': {'temp': 294.07, 'feels_like': 293.16, 'temp_min': 294.07, 'temp_max': 294.07, 'pressure': 1023, 'sea_level': 1023, 'grnd_level': 1020, 'humidity': 36, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03d'}], 'clouds': {'all': 26}, 'wind': {'speed': 2.02, 'deg': 209, 'gust': 3.27}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-29 09:00:00'}, {'dt': 1780056000, 'main': {'temp': 297.72, 'feels_like': 297.2, 'temp_min': 297.72, 'temp_max': 297.72, 'pressure': 1021, 'sea_level': 1021, 'grnd_level': 1019, 'humidity': 37, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 36}, 'wind': {'speed': 2.9, 'deg': 234, 'gust': 3.92}, 'visibility': 10000, 'pop': 0.2, 'rain': {'3h': 0.1}, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-29 12:00:00'}, {'dt': 1780066800, 'main': {'temp': 295.97, 'feels_like': 295.87, 'temp_min': 295.97, 'temp_max': 295.97, 'pressure': 1020, 'sea_level': 1020, 'grnd_level': 1018, 'humidity': 60, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 100}, 'wind': {'speed': 3.62, 'deg': 246, 'gust': 5.91}, 'visibility': 10000, 'pop': 0.27, 'rain': {'3h': 0.18}, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-29 15:00:00'}, {'dt': 1780077600, 'main': {'temp': 293.62, 'feels_like': 293.89, 'temp_min': 293.62, 'temp_max': 293.62, 'pressure': 1019, 'sea_level': 1019, 'grnd_level': 1017, 'humidity': 83, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 100}, 'wind': {'speed': 2.1, 'deg': 223, 'gust': 4.96}, 'visibility': 10000, 'pop': 0.2, 'rain': {'3h': 0.35}, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-29 18:00:00'}, {'dt': 1780088400, 'main': {'temp': 289.32, 'feels_like': 289.53, 'temp_min': 289.32, 'temp_max': 289.32, 'pressure': 1019, 'sea_level': 1019, 'grnd_level': 1017, 'humidity': 97, 'temp_kf': 0}, 'weather': [{'id': 501, 'main': 'Rain', 'description': 'moderate rain', 'icon': '10n'}], 'clouds': {'all': 100}, 'wind': {'speed': 2.47, 'deg': 278, 'gust': 4.75}, 'visibility': 2997, 'pop': 1, 'rain': {'3h': 4.48}, 'sys': {'pod': 'n'}, 'dt_txt': '2026-05-29 21:00:00'}, {'dt': 1780099200, 'main': {'temp': 285.43, 'feels_like': 285.25, 'temp_min': 285.43, 'temp_max': 285.43, 'pressure': 1019, 'sea_level': 1019, 'grnd_level': 1016, 'humidity': 97, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10n'}], 'clouds': {'all': 99}, 'wind': {'speed': 2.57, 'deg': 284, 'gust': 8.05}, 'visibility': 10000, 'pop': 1, 'rain': {'3h': 0.8}, 'sys': {'pod': 'n'}, 'dt_txt': '2026-05-30 00:00:00'}, {'dt': 1780110000, 'main': {'temp': 283.5, 'feels_like': 283.15, 'temp_min': 283.5, 'temp_max': 283.5, 'pressure': 1019, 'sea_level': 1019, 'grnd_level': 1016, 'humidity': 98, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 9}, 'wind': {'speed': 2.62, 'deg': 281, 'gust': 8.95}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-30 03:00:00'}, {'dt': 1780120800, 'main': {'temp': 287.27, 'feels_like': 287.09, 'temp_min': 287.27, 'temp_max': 287.27, 'pressure': 1019, 'sea_level': 1019, 'grnd_level': 1017, 'humidity': 90, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 10}, 'wind': {'speed': 3.43, 'deg': 289, 'gust': 8.38}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-30 06:00:00'}, {'dt': 1780131600, 'main': {'temp': 292.92, 'feels_like': 292.44, 'temp_min': 292.92, 'temp_max': 292.92, 'pressure': 1018, 'sea_level': 1018, 'grnd_level': 1016, 'humidity': 57, 'temp_kf': 0}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02d'}], 'clouds': {'all': 21}, 'wind': {'speed': 5.41, 'deg': 295, 'gust': 7.96}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-30 09:00:00'}, {'dt': 1780142400, 'main': {'temp': 294.17, 'feels_like': 293.66, 'temp_min': 294.17, 'temp_max': 294.17, 'pressure': 1018, 'sea_level': 1018, 'grnd_level': 1016, 'humidity': 51, 'temp_kf': 0}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02d'}], 'clouds': {'all': 15}, 'wind': {'speed': 5.78, 'deg': 300, 'gust': 7.93}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-30 12:00:00'}, {'dt': 1780153200, 'main': {'temp': 293.48, 'feels_like': 292.93, 'temp_min': 293.48, 'temp_max': 293.48, 'pressure': 1017, 'sea_level': 1017, 'grnd_level': 1015, 'humidity': 52, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03d'}], 'clouds': {'all': 27}, 'wind': {'speed': 5.22, 'deg': 301, 'gust': 6.78}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-30 15:00:00'}, {'dt': 1780164000, 'main': {'temp': 290.01, 'feels_like': 289.55, 'temp_min': 290.01, 'temp_max': 290.01, 'pressure': 1017, 'sea_level': 1017, 'grnd_level': 1014, 'humidity': 69, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03d'}], 'clouds': {'all': 36}, 'wind': {'speed': 3.34, 'deg': 294, 'gust': 5.91}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-30 18:00:00'}, {'dt': 1780174800, 'main': {'temp': 284.51, 'feels_like': 284.16, 'temp_min': 284.51, 'temp_max': 284.51, 'pressure': 1016, 'sea_level': 1016, 'grnd_level': 1013, 'humidity': 94, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03n'}], 'clouds': {'all': 34}, 'wind': {'speed': 1.96, 'deg': 296, 'gust': 2.74}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-05-30 21:00:00'}, {'dt': 1780185600, 'main': {'temp': 283.05, 'feels_like': 283.05, 'temp_min': 283.05, 'temp_max': 283.05, 'pressure': 1014, 'sea_level': 1014, 'grnd_level': 1012, 'humidity': 94, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03n'}], 'clouds': {'all': 28}, 'wind': {'speed': 1.1, 'deg': 280, 'gust': 1.1}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-05-31 00:00:00'}, {'dt': 1780196400, 'main': {'temp': 282.37, 'feels_like': 282.37, 'temp_min': 282.37, 'temp_max': 282.37, 'pressure': 1013, 'sea_level': 1013, 'grnd_level': 1011, 'humidity': 94, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'clouds': {'all': 57}, 'wind': {'speed': 1.2, 'deg': 288, 'gust': 1.17}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-31 03:00:00'}, {'dt': 1780207200, 'main': {'temp': 287.89, 'feels_like': 287.3, 'temp_min': 287.89, 'temp_max': 287.89, 'pressure': 1012, 'sea_level': 1012, 'grnd_level': 1010, 'humidity': 72, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'clouds': {'all': 57}, 'wind': {'speed': 1.31, 'deg': 272, 'gust': 2.37}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-31 06:00:00'}, {'dt': 1780218000, 'main': {'temp': 290.12, 'feels_like': 289.65, 'temp_min': 290.12, 'temp_max': 290.12, 'pressure': 1012, 'sea_level': 1012, 'grnd_level': 1009, 'humidity': 68, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 100}, 'wind': {'speed': 2.32, 'deg': 260, 'gust': 3.44}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-31 09:00:00'}, {'dt': 1780228800, 'main': {'temp': 293.31, 'feels_like': 293.05, 'temp_min': 293.31, 'temp_max': 293.31, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 1008, 'humidity': 64, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 96}, 'wind': {'speed': 3.26, 'deg': 283, 'gust': 4.71}, 'visibility': 10000, 'pop': 0.28, 'rain': {'3h': 0.5}, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-31 12:00:00'}, {'dt': 1780239600, 'main': {'temp': 293.62, 'feels_like': 293.18, 'temp_min': 293.62, 'temp_max': 293.62, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 1008, 'humidity': 56, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 46}, 'wind': {'speed': 4.57, 'deg': 313, 'gust': 5.58}, 'visibility': 10000, 'pop': 0.85, 'rain': {'3h': 0.83}, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-31 15:00:00'}, {'dt': 1780250400, 'main': {'temp': 290.29, 'feels_like': 289.78, 'temp_min': 290.29, 'temp_max': 290.29, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 1008, 'humidity': 66, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'clouds': {'all': 54}, 'wind': {'speed': 2.99, 'deg': 301, 'gust': 5.85}, 'visibility': 10000, 'pop': 0.56, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-31 18:00:00'}, {'dt': 1780261200, 'main': {'temp': 285.56, 'feels_like': 285.21, 'temp_min': 285.56, 'temp_max': 285.56, 'pressure': 1011, 'sea_level': 1011, 'grnd_level': 1008, 'humidity': 90, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04n'}], 'clouds': {'all': 77}, 'wind': {'speed': 2.46, 'deg': 269, 'gust': 7.63}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-05-31 21:00:00'}, {'dt': 1780272000, 'main': {'temp': 283.94, 'feels_like': 283.63, 'temp_min': 283.94, 'temp_max': 283.94, 'pressure': 1011, 'sea_level': 1011, 'grnd_level': 1009, 'humidity': 98, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04n'}], 'clouds': {'all': 62}, 'wind': {'speed': 3, 'deg': 249, 'gust': 8.89}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-06-01 00:00:00'}, {'dt': 1780282800, 'main': {'temp': 283.01, 'feels_like': 281.56, 'temp_min': 283.01, 'temp_max': 283.01, 'pressure': 1011, 'sea_level': 1011, 'grnd_level': 1008, 'humidity': 98, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 88}, 'wind': {'speed': 2.88, 'deg': 240, 'gust': 9.29}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-01 03:00:00'}, {'dt': 1780293600, 'main': {'temp': 287.33, 'feels_like': 286.84, 'temp_min': 287.33, 'temp_max': 287.33, 'pressure': 1011, 'sea_level': 1011, 'grnd_level': 1008, 'humidity': 78, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'clouds': {'all': 75}, 'wind': {'speed': 3.8, 'deg': 239, 'gust': 7.26}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-01 06:00:00'}, {'dt': 1780304400, 'main': {'temp': 288.45, 'feels_like': 288.18, 'temp_min': 288.45, 'temp_max': 288.45, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 1008, 'humidity': 82, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 100}, 'wind': {'speed': 3.76, 'deg': 223, 'gust': 6.99}, 'visibility': 10000, 'pop': 0.33, 'rain': {'3h': 0.21}, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-01 09:00:00'}, {'dt': 1780315200, 'main': {'temp': 291.18, 'feels_like': 291.08, 'temp_min': 291.18, 'temp_max': 291.18, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 1008, 'humidity': 78, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 98}, 'wind': {'speed': 3.94, 'deg': 264, 'gust': 6.12}, 'visibility': 10000, 'pop': 1, 'rain': {'3h': 2.16}, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-01 12:00:00'}], 'city': {'id': 2911298, 'name': 'Hamburg', 'coord': {'lat': 53.55, 'lon': 10}, 'country': 'DE', 'population': 1739117, 'timezone': 7200, 'sunrise': 1779850973, 'sunset': 1779910303}}

Bringing together our chosen columns

In [11]:
weather_items = []

for item in json["list"]:
    weather_item = {
        "forecast_time": item.get("dt_txt", None),
        "temperature": item["main"].get("temp", None),
        "forecast": item["weather"][0].get("main", None),
        "rain_in_last_3h": item.get("rain", {}).get("3h", 0),
        "wind_speed": item["wind"].get("speed", None),        
    }

    weather_items.append(weather_item)

weather_df = pd.DataFrame(weather_items)

weather_df.head()

         forecast_time  temperature forecast  rain_in_last_3h  wind_speed
0  2026-05-27 15:00:00       292.78    Clear              0.0        5.15
1  2026-05-27 18:00:00       291.40    Clear              0.0        4.27
2  2026-05-27 21:00:00       286.85    Clear              0.0        2.53
3  2026-05-28 00:00:00       281.49    Clear              0.0        2.20
4  2026-05-28 03:00:00       280.09    Clear              0.0        2.10

## Creating function for multiple cities

In [12]:
from zoneinfo import ZoneInfo

In [ ]:
def get_weather_data(cities):
  # Let's ensure the timezone is our local timezone
  berlin_timezone = ZoneInfo('Europe/Berlin')
  API_key = os.getenv("OPENWEATHER_API_KEY")
  weather_items = []

  for city in cities:

    country = "DE"

    # Geocoder api to get the latitude and longitude
    # This information should be from your SQL table, but we don't have that here
    url = (f"http://api.openweathermap.org/geo/1.0/direct?q={city},{country}&limit=5&appid={API_key}")
    response = requests.get(url)
    json = response.json()   
    latitude = json[0]["lat"]
    longitude = json[0]["lon"]

    # weather api
    weather_url = (f"https://api.openweathermap.org/data/2.5/forecast?lat={latitude}&lon={longitude}&appid={API_key}&units=metric")
    weather_response = requests.get(weather_url)
    weather_json = weather_response.json()

    # Added the time retrieved so we know when the forecast was made
    retrieval_time = datetime.now(berlin_timezone).strftime("%Y-%m-%d %H:%M:%S")

    for item in weather_json["list"]:
        weather_item = {
            # Added the city name, so the information is clear when looking at multiple cities
            "city": city,
            "forecast_time": item.get("dt_txt", None),
            "temperature": item["main"].get("temp", None),
            "forecast": item["weather"][0].get("main", None),
            "rain_in_last_3h": item.get("rain", {}).get("3h", 0),
            "wind_speed": item["wind"].get("speed", None),
            "data_retrieved_at": retrieval_time
        }

        weather_items.append(weather_item)

  weather_df = pd.DataFrame(weather_items)

  return weather_df

In [16]:
get_weather_data(["Berlin", "Hamburg", "Munich"])

,city,forecast_time,temperature,forecast,rain_in_last_3h,wind_speed,data_retrieved_at
0,Berlin,2026-05-27 15:00:00,23.14,Clear,0.00,5.48,2026-05-27 16:00:20
1,Berlin,2026-05-27 18:00:00,22.11,Clear,0.00,5.19,2026-05-27 16:00:20
2,Berlin,2026-05-27 21:00:00,17.23,Clouds,0.00,2.85,2026-05-27 16:00:20
3,Berlin,2026-05-28 00:00:00,13.41,Clouds,0.00,2.80,2026-05-27 16:00:20
4,Berlin,2026-05-28 03:00:00,10.83,Clear,0.00,2.77,2026-05-27 16:00:20
...,...,...,...,...,...,...,...
115,Munich,2026-06-01 00:00:00,12.04,Rain,0.93,3.08,2026-05-27 16:00:20
116,Munich,2026-06-01 03:00:00,10.99,Clouds,0.00,3.16,2026-05-27 16:00:20
117,Munich,2026-06-01 06:00:00,14.42,Clouds,0.00,3.24,2026-05-27 16:00:20
118,Munich,2026-06-01 09:00:00,19.19,Clear,0.00,3.45,2026-05-27 16:00:20
119,Munich,2026-06-01 12:00:00,19.93,Clouds,0.00,3.10,2026-05-27 16:00:20

In [17]:
weather_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   forecast_time    40 non-null     str
 1   temperature      40 non-null     float64
 2   forecast         40 non-null     str
 3   rain_in_last_3h  40 non-null     float64
 4   wind_speed       40 non-null     float64
dtypes: float64(3), str(2)
memory usage: 1.7 KB

# Making our function work with our SQL cities data
This section delves into a more advanced aspect of the project, which may be beyond the point many of you got to. However, it serves as an illustrative example of how to structure your work effectively. It demonstrates how we can compartmentalise various aspects of our data processing pipeline into distinct functions, enhancing code readability and facilitating debugging.

```sql
-- Create the 'weather' table
CREATE TABLE weather (
    city_id INT NOT NULL,
    forecast_time DATETIME NOT NULL,
    temperature FLOAT,
    forecast VARCHAR(255),
    rain_in_last_3h FLOAT,
    wind_speed FLOAT,
    data_retrieved_at DATETIME NOT NULL,

    PRIMARY KEY (city_id, forecast_time),

    FOREIGN KEY (city_id)
        REFERENCES cities(city_id)
);
```

In [23]:
schema = "wikipedia"
host = "127.0.0.1"
user = "root"
password = os.getenv("DB_PASSWORD")
port = 3306

connection_string = f'mysql+pymysql://{user}:{password}@{host}:{port}/{schema}'

In [ ]:
def retrieve_and_send_data():

  def _create_connection_string():
    schema = "wikipedia"
    host = "127.0.0.1"
    user = "root"
    password = os.getenv("DB_PASSWORD")
    port = 3306
    return f'mysql+pymysql://{user}:{password}@{host}:{port}/{schema}'

  def _get_cities_data(connection_string):
    return pd.read_sql("cities", con=connection_string)

  def _get_weather_data(cities_df):
    berlin_timezone = ZoneInfo('Europe/Berlin')
    API_key = os.getenv("OPENWEATHER_API_KEY")
    weather_items = []

    for _, city in cities_df.iterrows():
        latitude = city["latitude"]
        longitude = city["longitude"]
        city_id = city["city_id"]

        url = (f"https://api.openweathermap.org/data/2.5/forecast?lat={latitude}&lon={longitude}&appid={API_key}&units=metric")
        response = requests.get(url)
        weather_data = response.json()

        retrieval_time = datetime.now(berlin_timezone).strftime("%Y-%m-%d %H:%M:%S")

        for item in weather_data["list"]:
            weather_item = {
                "city_id": city_id,
                "forecast_time": item.get("dt_txt"),
                "temperature": item["main"].get("temp"),
                "forecast": item["weather"][0].get("main"),
                "rain_in_last_3h": item.get("rain", {}).get("3h", 0),
                "wind_speed": item["wind"].get("speed"),
                "data_retrieved_at": retrieval_time
            }
            weather_items.append(weather_item)

    weather_df = pd.DataFrame(weather_items)
    weather_df["forecast_time"] = pd.to_datetime(weather_df["forecast_time"])
    weather_df["data_retrieved_at"] = pd.to_datetime(weather_df["data_retrieved_at"])

    return weather_df

  def _store_weather_data(weather_df, connection_string):
    weather_df.to_sql('weather',
                      if_exists='append',
                      con=connection_string,
                      index=False)

  connection_string = _create_connection_string()
  cities_df = _get_cities_data(connection_string)
  weather_df = _get_weather_data(cities_df)
  _store_weather_data(weather_df, connection_string)
  return "Data has been updated"

In [25]:
retrieve_and_send_data()

'Data has been updated'

In [26]:
pd.read_sql("weather", con=connection_string)

,city_id,forecast_time,temperature,forecast,rain_in_last_3h,wind_speed,data_retrieved_at
0,1,2026-05-27 15:00:00,23.32,Clear,0.00,5.48,2026-05-27 16:01:38
1,1,2026-05-27 18:00:00,22.23,Clear,0.00,5.19,2026-05-27 16:01:38
2,1,2026-05-27 21:00:00,17.29,Clouds,0.00,2.85,2026-05-27 16:01:38
3,1,2026-05-28 00:00:00,13.41,Clouds,0.00,2.80,2026-05-27 16:01:38
4,1,2026-05-28 03:00:00,10.83,Clear,0.00,2.77,2026-05-27 16:01:38
...,...,...,...,...,...,...,...
115,3,2026-06-01 00:00:00,12.04,Rain,0.93,3.08,2026-05-27 16:01:39
116,3,2026-06-01 03:00:00,10.99,Clouds,0.00,3.16,2026-05-27 16:01:39
117,3,2026-06-01 06:00:00,14.42,Clouds,0.00,3.24,2026-05-27 16:01:39
118,3,2026-06-01 09:00:00,19.19,Clear,0.00,3.45,2026-05-27 16:01:39
119,3,2026-06-01 12:00:00,19.93,Clouds,0.00,3.10,2026-05-27 16:01:39